### ISSUE TITLE
Seeking past end of file is untested

### ISSUE THREAD

**Issue by marvingreenberg** [rfk/filelike#2]
I quickly added a test to TestReadWriteSeek:
    # When resizable
    def test_seek_past_end(self):
        self.file.seek(11,2)
        self.assertEquals(self.file.tell(),11 + len(self.contents)) 

And quickly get the expected failures for a variety of non resizable derivatives (which apparently set the file pointer to self.stop).  But then I became uncertain what the "correct" behavior of seeking past the end is.  lseek/fseek man pages seem to suggest that seeking past the end is perfectly legal (and should not change the file size), which seems to suggest that even when not resizable, seeks past end should set the position past the end.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
